### ISSUE TITLE
PRs?

### ISSUE THREAD

**Issue by williamsbdev** [layervault/ember-cli-stripejs#1]
I've created [ember-cli-stripe-custom-form](https://github.com/williamsbdev/ember-cli-stripe-custom-form) for Stripe when using the JS for a custom form. Would you consider accepting some of my modifications? Particularly the changes to the [index.js](https://github.com/williamsbdev/ember-cli-stripe-custom-form/blob/master/index.js). This would allow you to run tests without any issue. I would like to not maintain another npm module/ember-addon and piggy back off of the awesome work you've already done.

Thanks!
Brandon

**Comment by kellysutton** [comment]
Hi @williamsbdev, 

Send the PR our way. One note that we can address fully in the PR: because Stripe has a "test mode," you probably won't want to stub the `Stripe` object out on anything `!production`. Also, I usually don't like to have application-level code aware of its environment and instead use feature flags, e.g. `config.APP.stubStripeRequests`.

Let me know if you have any questions.
